name: Deployment
on:
  push:
    branches:
      - main
jobs:
  terraform_init_plan_apply:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ap-southeast-1

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2
      with:
        terraform_wrapper: false

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./prod/ap-southeast-1/storage/s3
    
    - name: Terraform plan
      run: terraform plan
      working-directory: ./prod/ap-southeast-1/storage/s3
    
    - name: Terraform apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: ./prod/ap-southeast-1/storage/s3
    
    - name: Terraform output
      run: |
        terraform output -json > terraform-outputs.json
        cat terraform-outputs.json
      working-directory: ./prod/ap-southeast-1/storage/s3